language: rust
rust:
  - stable

before_script: |
  rustup component add rustfmt-preview &&
  rustup component add clippy-preview &&
  sudo apt-get update &&
  sudo apt-get install libdbus-1-dev
script: |
  cargo fmt -- --check &&
  cargo clippy -- -D clippy &&
  cargo build --verbose &&
  cargo test  --verbose
cache: cargo
